### PR TITLE
Update "Get involved" page

### PR DESCRIPTION
**Pull request by martin-g**
Trying to update the web site with the changes from https://github.com/apache/velocity-site/pull/1 but the generated HTML is not the expected. A big part of it is lost...

Here is the script I use to generate the site (slightly modified version of the one at http://velocity.apache.org/site-building.html)

```
#!/usr/bin/env bash

export MARKDOWN_SOCKET=/tmp/markdown
CMS=/home/martin/svn/apache/cms/
VELOCITY=/home/martin/git/apache/velocity

if [[ `pidof markdownd.py` == "" ]]; then
   python2 $CMS/build/markdownd.py
fi

pushd $VELOCITY/velocity-site
git reset --hard
git checkout master
git up

find $VELOCITY/velocity-site/src/content -name "*~" | xargs rm -v
rm -rf $VELOCITY/velocity-site-target/*
rm -rf $VELOCITY/velocity-site-target/.htaccess

echo Generating site...

$CMS/build/build_site.pl --source-base $VELOCITY/velocity-site/src --target-base $VELOCITY/velocity-site-target

echo Copying to production directory...

git checkout asf-site
git up

rm -rf $VELOCITY/velocity-site/* $VELOCITY/velocity-site/.htaccess
cp -r $VELOCITY/velocity-site-target/content/* $VELOCITY/velocity-site/
cp -r $VELOCITY/velocity-site-target/content/.htaccess $VELOCITY/velocity-site/

echo Post processing...

find $VELOCITY/velocity-site/ -name "*.html" | xargs sed -ri -e "s'<span></span>''g"

git st
popd
```

### CODE REVIEW

**Comment by arkanovicz** [comment]
Here is [a patched version](https://gist.github.com/arkanovicz/acf7c1249437e701f586a2773ac74f62) of the apache-cms' markdown daemon which produces some log in `/tmp/markdown.debug.log` and `/tmp/markdown.error.log`. You can even log everything received and sent by uncommenting logging lines within it (I did what I could, I'm no python expert either).

It doesn't daemonize itself, so use something like `kill $(pidof markdown-debug.py)` from another console to stop it.

I hope it can help you identify the error. Which parts aren't generated?

I think the best way to go would be to be able to produce a Dockerfile running the markdown daemon. Then  a single script shell could generate the site, that would even run on windows.

**Comment by martin-g** [comment]
`/tmp/markdown.debug.log` produces `INFO:root:Markdown daemon running.`. 
`/tmp/markdown.error.log` remains empty.

> Which parts aren't generated?

See the diff in this PR. 
I expect to see a diff about this change: https://github.com/apache/velocity-site/pull/1/files#diff-457c05e02d721acb5acba9498a687000a474a871fe9c769a49ceed534e6b2dbdR22 but actually it removes a big part of the HTML (the navigation on the left and the content). I've pushed only `get-involved.html` but all other HTML files produced by `build-site.pl` have the same problem.

**Comment by martin-g** [comment]
This PR is ready for review.
I've created it by following the steps described in https://github.com/apache/velocity-site/pull/5

**Comment by martin-g** [comment]
As per https://github.com/apache/velocity-site/pull/5#issuecomment-769725648 only committers should commit to `asf-site` branch.
Closing this PR!

**Pull request closed without merging**
