### PR TITLE
Update build steps in README and Get Involved page

### PR DESCRIPTION
**Pull request by martin-g**

### CODE REVIEW

**Comment by martin-g** [comment]
At the moment README is a .txt file. IMO it would be better to convert it to .md but in a separate PR.

**Comment by arkanovicz** [comment]
Nice!

Yres, an md file would be better.

And it should be mentioned somewhere that one needs to have docker installed to use the site builder.

**Comment by arkanovicz** [comment]
Also, let's tell contributors that they only need to submit a PR towards master. Locally building in asf-site is a mean for them to control what changed, and to open the result in their browser, but we'll anyway build the proposed changes locally to check the result, so let's relieve the contributors of the need to submit the second PR.

**Comment by martin-g** [comment]
I've updated the PR with your suggestions!

**Comment by arkanovicz** [comment]
Looks fine to me. Thanks.

**Comment by martin-g** [comment]
Thank you for your help, @arkanovicz !

**Pull request merged**
