### PR TITLE
Update docu about contributing patches/PRs

### PR DESCRIPTION
**Pull request by martin-g**
Fix few minor typos in README.txt

### CODE REVIEW

**Comment by martin-g** [comment]
I have the feeling that the information in the README.txt is not accurate anymore. There is no `tools/` folder and I was not able to generate `.html` files out of the `.mdtext` ones.

**Comment by martin-g** [comment]
Any comments on the proposed changes ?

**Comment by arkanovicz** [comment]
Hello.

The site building instructions are obsolete too, it's not using maven for the time being. The almost up-to-date informations (not yet taking out the migration to gitbox) are [here](http://velocity.apache.org/site-building.html).

The remaining looks ok.

**Comment by martin-g** [comment]
So it still uses Apache CMS ? I thought this service is no more available and all projects have to use static site generators (like the mentioned `pelican`).
I'll see how this works!

**Comment by arkanovicz** [comment]
It just uses a local checkout of the Apache CMS (without the CMS feature itself, of course). The plan is to move to something else (maybe [Pelican](https://github.com/getpelican/pelican), or why not an hosted J2EE webapp using [Velocity markdown templates](https://github.com/arkanovicz/velocity-markdown-directive)?).

**Comment by martin-g** [comment]
I am not sure I will be able to do it with Apache CMS :-/

Disclaimer: I am not very deep into Python!
I use Ubuntu 20.10 and there is no `pip2` package anymore, so I am not able to install the required `markdown` module/package.

Even https://bootstrap.pypa.io/get-pip.py does not work:
```
sudo python2 get-pip.py
Traceback (most recent call last):
  File "get-pip.py", line 24226, in <module>
    main()
  File "get-pip.py", line 199, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    from pip._internal.cli.main import main as pip_entry_point
  File "/tmp/tmpNh7KcV/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
```

**Comment by arkanovicz** [comment]
I have the same ubuntu, but with a python 2.7 markdown in `/usr/local/lib/python2.7/dist-packages/markdown/`, so I imagine it was installed by pip2.

The error you get with get-pip is [referenced on SO](https://stackoverflow.com/a/65866547/710286) : you need to use `https://bootstrap.pypa.io/2.7/get-pip.py` now.

**Comment by martin-g** [comment]
@arkanovicz Thanks for the new url! The markdown module has been installed successfully for Python2 here! I also needed to install Perl's LWP::Simple (`cpan install LWP::Simple`).
But the generated HTML misses big chunks of the old one. See https://github.com/apache/velocity-site/pull/2 for more.

**Comment by arkanovicz** [comment]
It's not the python markdown daemon which is at fault, but the perl building script. The missing parts all correspond to dynamic sections in the [skeleton](https://github.com/apache/velocity-site/blob/trunk/cms/trunk/templates/skeleton.html).

I give the docker solution a try and let you know.

**Comment by arkanovicz** [comment]
The dockerized site builder is functional.

The single shell script `velocity-site/builder/bin/builder.sh` should do all the work.

I think your setup was lacking some perl dependency (like xsltproc), and also the optional python Pygments package. Also, both versions of Markdown and Pygments have to be carefully chosen. All that is now taken care of in the dockerfile.

The script can be symlinked like in:

    ln -s ../path/to/velocity-site/builder/bin/builder.sh ~/bin/velsite

Please let me know if it's functional for you.

**Comment by martin-g** [comment]
I am testing it now!

But you pushed to `trunk` branch while the README file says: `Note: the branch trnk is obsolete. Please use the master branch.`

**Comment by martin-g** [comment]
It almost works!
1) I needed to use `trunk` branch. I am not sure whether this is correct. See my previous message above
2) The `get-involved.html` file is properly recreated now! But many other files are deleted, e.g.
```
D tools/devel/apidocs/org/apache/velocity/tools/view/jsp/jspimpl/class-use/ExternalWriterHttpServletResponse.html
 D tools/devel/apidocs/org/apache/velocity/tools/view/jsp/jspimpl/class-use/JspUtils.html
 D tools/devel/apidocs/org/apache/velocity/tools/view/jsp/jspimpl/class-use/JspWriterImpl.html
 D tools/devel/apidocs/org/apache/velocity/tools/view/jsp/jspimpl/class-use/VelocityBodyContent.html
 D tools/devel/apidocs/org/apache/velocity/tools/view/jsp/jspimpl/class-use/VelocityJspFragment.html
 D tools/devel/apidocs/org/apache/velocity/tools/view/jsp/jspimpl/class-use/VelocityPageContext.html
 D tools/devel/apidocs/org/apache/velocity/tools/view/jsp/jspimpl/class-use/VelocityToolsJspException.html
```
and many more. Maybe this is related to 1)
3) I am not sure how convenient the auto cloning to ../velocity-site-production is. I cannot push there, so I need to add my fork as a Git remote anyway. GitBox is not really useful for contributors

**Comment by arkanovicz** [comment]
Sorry for the branches error. Yes, you have to use master. The default branch on github is still trunk but the fix is ongoing.

The cloning of the production branch now uses github (on master!).

I hope the missing files were a consequence of (1), you'll tell me.

**Comment by martin-g** [comment]
Everything works fine now!
Both this PR and https://github.com/apache/velocity-site/pull/2 are ready to be merged !

**Comment by martin-g** [comment]
Actually with this PR I will update the README with the new site building steps

**Comment by martin-g** [comment]
Closing in favor of https://github.com/apache/velocity-site/pull/5

**Pull request closed without merging**
